services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    entrypoint: /bin/sh
    command: >
      -c "ollama serve & sleep 5 && ollama pull llama3.2 && ollama pull nomic-embed-text && ollama pull llama3.2-vision && wait"

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
    depends_on:
      - ollama
    volumes:
      - ./app:/app
